import dryFish from '../../assets/fish.png';
import rice from '../../assets/rice.png';
import tomato from '../../assets/tomato.png'



export const orders = [
  {
    id: "#28392OD",
    customer: "Marvin McKinney",
    email: "marvinmckinney@email.com",
    phone: "(808) 555-0111",
    address: "3891 Ranchview Dr. Richardson, California 62639",
    totalAmount: "£43.00",
    paymentStatus: "PAID",
    totalItems: 3,
    date: "Oct 1, 05:53 PM",
    status: "Pending",
    products: [
      {
        name: "Red Tomato Ball",
        price: "£13.00",
        qty: 12,
        status: "Pending",
        img:dryFish
      },
      { name: "Dry fish panla egun (eja kika)", price: "£16.00", qty: 6, status: "Pending",img:dryFish},
      { name: "Ofada Rice", price: "£11.00", qty: 1, status: "Pending", img:dryFish},
    ],
  },
  {
    id: "#01293KS",
    customer: "Leslie Alexander",
    email: "leslie.alexander@email.com",
    phone: "(808) 555-0123",
    address: "3891 Ranchview Dr. Richardson, California 62639",
    totalAmount: "£29.00",
    paymentStatus: "PAID",
    totalItems: 2,
    date: "Oct 2, 08:53 AM",
    status: "Delivered",
    products: [
      { name: "Basmati Rice", price: "£15.00", qty: 5, status: "Delivered",img:dryFish },
      { name: "Plantain Chips", price: "£14.00", qty: 3, status: "Delivered",img:dryFish },
    ],
  },
  {
    id: "#92832M",
    customer: "Devon Lane",
    email: "devon.lane@email.com",
    phone: "(808) 555-0145",
    address: "3891 Ranchview Dr. Richardson, California 62639",
    totalAmount: "£120.00",
    paymentStatus: "PAID",
    totalItems: 3,
    date: "Sep 24, 10:03 AM",
    status: "Cancelled",
  
    products: [
      { name: "Frozen Chicken", price: "£40.00", qty: 2, status: "Cancelled",img:dryFish },
      { name: "Yam Tubers", price: "£35.00", qty: 1, status: "Cancelled",img:dryFish },
      { name: "Palm Oil", price: "£45.00", qty: 1, status: "Cancelled",img:dryFish },
    ],
  },
  {
    id: "#76289TR",
    customer: "Cameron Williamson",
    email: "cameron.williamson@email.com",
    phone: "(808) 555-0198",
    address: "3891 Ranchview Dr. Richardson, California 62639",
    totalAmount: "£75.00",
    paymentStatus: "PAID",
    totalItems: 4,
    date: "Sep 28, 01:45 PM",
    status: "Pending",
    products: [
      { name: "Groundnut Oil", price: "£20.00", qty: 1, status: "Pending",img:dryFish },
      { name: "Cashew Nuts", price: "£25.00", qty: 2, status: "Pending",img:dryFish },
      { name: "Honey", price: "£30.00", qty: 1, status: "Pending",img:dryFish },
    ],
  },
  {
    id: "#99282LW",
    customer: "Eleanor Pena",
    email: "eleanor.pena@email.com",
    phone: "(808) 555-0222",
    address: "3891 Ranchview Dr. Richardson, California 62639",
    totalAmount: "£55.00",
    paymentStatus: "PAID",
    totalItems: 3,
    date: "Sep 30, 07:10 AM",
    status: "Delivered",
    products: [
      { name: "Beans Flour", price: "£18.00", qty: 2, status: "Delivered",img:dryFish },
      { name: "Coconut Oil", price: "£17.00", qty: 1, status: "Delivered",img:dryFish },
      { name: "Avocado", price: "£20.00", qty: 4, status: "Delivered",img:dryFish },
    ],
  },
  {
    id: "#33819XY",
    customer: "Guy Hawkins",
    email: "guy.hawkins@email.com",
    phone: "(808) 555-0333",
    address: "3891 Ranchview Dr. Richardson, California 62639",
    totalAmount: "£88.00",
    paymentStatus: "PENDING",
    totalItems: 5,
    date: "Oct 5, 03:23 PM",
    status: "Pending",
    products: [
      { name: "Banana", price: "£22.00", qty: 5, status: "Pending",img:dryFish },
      { name: "Pineapple", price: "£33.00", qty: 2, status: "Pending",img:dryFish },
      { name: "Oranges", price: "£33.00", qty: 6, status: "Pending",img:dryFish },
    ],
  },
  {
    id: "#44821GT",
    customer: "Annette Black",
    email: "annette.black@email.com",
    phone: "(808) 555-0444",
    address: "3891 Ranchview Dr. Richardson, California 62639",
    totalAmount: "£64.00",
    paymentStatus: "PAID",
    totalItems: 2,
    date: "Oct 7, 09:15 AM",
    status: "Cancelled",
    products: [
      { name: "Goat Meat", price: "£34.00", qty: 2, status: "Cancelled",img:dryFish },
      { name: "Cow Skin (Ponmo)", price: "£30.00", qty: 3, status: "Cancelled",img:dryFish },
    ],
  },
  {
    id: "#59310RT",
    customer: "Bessie Cooper",
    email: "bessie.cooper@email.com",
    phone: "(808) 555-0555",
    address: "3891 Ranchview Dr. Richardson, California 62639",
    totalAmount: "£112.00",
    paymentStatus: "PAID",
    totalItems: 4,
    date: "Oct 10, 02:42 PM",
    status: "Delivered",
    products: [
      { name: "Oats", price: "£28.00", qty: 3, status: "Delivered",img:dryFish },
      { name: "Wheat Flour", price: "£29.00", qty: 1, status: "Delivered",img:dryFish },
      { name: "Corn Flakes", price: "£55.00", qty: 5, status: "Delivered",img:dryFish },
    ],
  },
  {
    id: "#67421BC",
    customer: "Ralph Edwards",
    email: "ralph.edwards@email.com",
    phone: "(808) 555-0666",
    address: "3891 Ranchview Dr. Richardson, California 62639",
    totalAmount: "£77.00",
    paymentStatus: "PAID",
    totalItems: 3,
    date: "Oct 12, 11:19 AM",
    status: "Pending",
    products: [
      { name: "Tomato Paste", price: "£20.00", qty: 4, status: "Pending",img:dryFish },
      { name: "Pepper Mix", price: "£27.00", qty: 3, status: "Pending",img:dryFish },
      { name: "Onions", price: "£30.00", qty: 2, status: "Pending",img:dryFish },
    ],
  },
  {
    id: "#78129ML",
    customer: "Kristin Watson",
    email: "kristin.watson@email.com",
    phone: "(808) 555-0777",
    address: "3891 Ranchview Dr. Richardson, California 62639",
    totalAmount: "£98.00",
    paymentStatus: "PAID",
    totalItems: 5,
    date: "Oct 15, 04:30 PM",
    status: "Cancelled",
    products: [
      { name: "Watermelon", price: "£33.00", qty: 2, status: "Cancelled",img:dryFish },
      { name: "Mango", price: "£28.00", qty: 3, status: "Cancelled",img:dryFish },
      { name: "Papaya", price: "£37.00", qty: 4, status: "Cancelled",img:dryFish },
    ],
  },
];
