export const orders = [
  {
    id: "#283920D",
    customer: "Marvin McKinney",
    totalAmount: "£43.00",
    status: "Pending",
    totalItems: 3,
    date: "Oct 1, 05:53 PM",
    products: [
      { name: "Red Tomato Ball", price: "£13.00", qty: 12, status: "Pending" },
      { name: "Dry Fish Panla Egun", price: "£16.00", qty: 6, status: "Pending" },
      { name: "Ofada Rice", price: "£11.00", qty: 1, status: "Pending" },
    ],
  },
  {
    id: "#012932KS",
    customer: "Leslie Alexander",
    totalAmount: "£29.00",
    status: "Delivered",
    totalItems: 8,
    date: "Oct 2, 08:53 AM",
    products: [],
  },
  {
    id: "#85392PL",
    customer: "Wade Warren",
    totalAmount: "£102.00",
    status: "Delivered",
    totalItems: 16,
    date: "Sep 18, 09:25 PM",
    products: [],
  },
  {
    id: "#92832M",
    customer: "Devon Lane",
    totalAmount: "£120,390.00",
    status: "Cancelled",
    totalItems: 307,
    date: "Sep 24, 10:03 AM",
    products: [],
  },
  {
    id: "#12819BV",
    customer: "Jenny Wilson",
    totalAmount: "£29,500.00",
    status: "Pending",
    totalItems: 89,
    date: "Sep 27, 07:53 AM",
    products: [],
  },
  {
    id: "#98234TR",
    customer: "Robert Fox",
    totalAmount: "£70.00",
    status: "Pending",
    totalItems: 4,
    date: "Oct 5, 02:15 PM",
    products: [],
  },
  {
    id: "#29432DK",
    customer: "Jane Cooper",
    totalAmount: "£350.00",
    status: "Cancelled",
    totalItems: 12,
    date: "Sep 20, 11:45 AM",
    products: [],
  },
  {
    id: "#56392RT",
    customer: "Ronald Richards",
    totalAmount: "£90.00",
    status: "Delivered",
    totalItems: 6,
    date: "Oct 3, 06:30 PM",
    products: [],
  },
  {
    id: "#67829JS",
    customer: "Floyd Miles",
    totalAmount: "£200.00",
    status: "Pending",
    totalItems: 10,
    date: "Oct 6, 09:10 AM",
    products: [],
  },
  {
    id: "#45632PO",
    customer: "Guy Hawkins",
    totalAmount: "£510.00",
    status: "Cancelled",
    totalItems: 20,
    date: "Sep 29, 03:20 PM",
    products: [],
  },
];
